name: Commit release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      nextVersion:
        description: 'Next version'
        required: true

jobs:
  commit-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-v${{ github.event.inputs.releaseVersion }}

      - name: Change Maven version to release version
        run: mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.releaseVersion }}

      - name: Commit release version update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prepare release ${{ github.event.inputs.releaseVersion }}

      - name: Change Maven version to next version
        run: mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.nextVersion }}-SNAPSHOT

      - name: Commit release version update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prepare next dev version ${{ github.event.inputs.nextVersion }}-SNAPSHOT

      - name: Create release pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: release-v${{ github.event.inputs.releaseVersion }}
          delete-branch: true