name: Commit release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      nextVersion:
        description: 'Next version'
        required: true

jobs:
  commit-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change Maven version to release version
        run: |
          git config user.name 'Farao GitHub Actions'
          git config user.email 'farao-community@rte-france.com'
          mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.releaseVersion }}
          git commit -am "Prepare release ${{ github.event.inputs.releaseVersion }}"
          mvn --batch-mode versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.nextVersion }}-SNAPSHOT
          git commit -am "Prepare next dev version ${{ github.event.inputs.nextVersion }}-SNAPSHOT"

      - name: Create release pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: release-v${{ github.event.inputs.releaseVersion }}
          delete-branch: true