name: Functional Tests

on: [push]

jobs:
  build:
    name: Run Cucumber Tests on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Download OR-Tools
        run: |
            Invoke-WebRequest -Uri "https://github.com/google/or-tools/releases/download/v9.5/ortools-win32-x86-64-9.5.2237.jar" -OutFile "${PWD}\\or-tools.jar"

      - name: Create OR-Tools install directory
        run: mkdir -p ${PWD}\\farao-dep\\runtime\\ortools\\lib\\

      - name: Install OR-Tools
        run: unzip -j ${PWD}\\or-tools.jar -d ${PWD}\\farao-dep\\runtime\\ortools\\lib\\ ortools-win32-x86-64/jniortools.dll

      - name: Cleanup workspace
        run: rm -Force ${PWD}\\or-tools.jar

      - name: Install OpenRAO with Maven
        run: mvn --batch-mode install -DskipTests=true

      - name: Run cucumber tests with Maven
        shell: bash
        run: export PATH=${PATH}:${PWD}\\farao-dep\\runtime\\ortools\\lib && mvn test -pl tests
