name: Cucumber Tests

on: [push]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: farao/farao-computation-base:1.7.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Run cucumber tests with Maven
        run: mvn test -pl tests
