name: Cucumber Tests

on: [push]

jobs:
  build:
    name: Run Cucumber Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install OR-Tools
        run: |
            curl https://github.com/google/or-tools/releases/download/v9.5/ortools-linux-x86-64-9.5.2237.jar --output /tmp/or-tools.jar \
              && mkdir -p ${PWD}/farao-dep/runtime/ortools/lib/ \
              && unzip -j /tmp/or-tools.jar -d ${PWD}/farao-dep/runtime/ortools/lib/ ortools-linux-x86-64/* \
              && rm -f ${PWD}/tmp/or-tools.jar

      - name: Run cucumber tests with Maven
        run: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/farao-dep/runtime/ortools/lib && mvn test -pl tests
