name: Functional Tests

on: [push]

jobs:
  cucumber_ubuntu:
    name: Run Cucumber tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Checkout powsybl-core sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/security_analysis_rewrite_operational_limits
      - name: Build and install powsybl-core with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-core/pom.xml install
      - name: Checkout powsybl-open-loadflow sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-open-loadflow
          ref: refs/heads/security_analysis_rewrite_operational_limits
      - name: Build and install powsybl-open-loadflow with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-open-loadflow/pom.xml install
      - name: Install OpenRAO with Maven
        run: mvn --batch-mode install -DskipTests=true
      - name: Run cucumber tests with Maven
        run: mvn test -pl tests

  cucumber_windows:
    name: Run Cucumber tests on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Checkout powsybl-core sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/security_analysis_rewrite_operational_limits
      - name: Build and install powsybl-core with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-core/pom.xml install
      - name: Checkout powsybl-open-loadflow sources
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-open-loadflow
          ref: refs/heads/security_analysis_rewrite_operational_limits
      - name: Build and install powsybl-open-loadflow with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-open-loadflow/pom.xml install
      - name: Install OpenRAO with Maven
        run: mvn --batch-mode install -DskipTests=true
      - name: Run cucumber tests with Maven
        shell: bash
        run: mvn test -pl tests
