name: Functional Tests

on: [push]

jobs:
  cucumber_tests:
    name: Run Cucumber tests on ${{ matrix.os }} with ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        jvm: [ java, graalvm ]
    steps:

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up Java 17
        if: matrix.jvm == 'java'
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup GraalVM
        if: matrix.jvm == 'graalvm'
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.12'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OpenRAO with Maven
        run: mvn --batch-mode install -DskipTests=true

      - name: Run cucumber tests with Maven
        run: mvn test -pl tests
