name: Cucumber Tests

on: [push]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run cucumber tests with Maven
        run: mvn test -pl tests -am
